### ISSUE TITLE
pumba netem command with docker network not working

### ISSUE THREAD

**Issue by sayankc** [alexei-led/pumba#137]
Hi ,
My requirement is to create a docker container within a specific docker network and apply network chaos only on that network.
Here is what I have done. But the delay is not working. only working with --interface eth0.

1. create a docker network.
`docker network create -d bridge --subnet 172.25.0.0/16 isolated_nw44`

2. Run a docker container in this network.
`docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --name=container44 --network=isolated_nw44 --ip=172.25.3.3 selenium/standalone-chrome`

3. check the network interface created, where the docker container is.
`ip addr |  grep 172.25` ==> inet 172.25.0.1/16 scope global br-72aff75d4744

4. Now applying netem on the new interface (br-72aff75d4744)
`./pumba_linux_amd64.v0.6.5 netem --duration 5m --interface br-72aff75d4744 --tc-image gaiadocker/iproute2 delay --time 1000 container44`

**Result : It is not resulting any additional delay for the URL**(http://<ip>:4444/)

5. **If I apply following command, netem is applying the delay but entire box network is impacted.**
`./pumba_linux_amd64.v0.6.5 netem --duration 5m --interface eth0 --tc-image gaiadocker/iproute2 delay --time 1000 container44`

**Comment by alexei-led** [comment]
@sayankc I will check it. 
Did you check with network interface assigned to your container (`container44`) binded to `isolated_nw44` network?

**Comment by sayankc** [comment]
hi @alexei-led ,
I checked with `isolated_nw44` too. Same result. network delay is not reflecting for the docker network. 
`./pumba_linux_amd64.v0.6.5 netem --duration 5m --interface isolated_nw44 --tc-image gaiadocker/iproute2 delay --time 1000 container44`

**Comment by sayankc** [comment]
Hi @alexei-led , 
Could you please let me know if it is fixed / planned to be fixed in next release.

**Comment by alexei-led** [comment]
Hi @sayankc 
Can you, please, post here output from `ifconfig` command running inside `container44`.

**Comment by alexei-led** [comment]
@sayankc does it work now? can I close the issue?

**Comment by sayankc** [comment]
@alexei-led , Issue is still there. I'll give you ifconfig.

**Comment by ebcFlagman** [comment]
I've the same issue.
Here's my docker-compose to reproduce:
```
version: '3'
services:
  web:
    image: nginx
  pinger:
    image: alpine
    command: "ping web1"
  pumba:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug netem --tc-image gaiadocker/iproute2 --duration 1m delay --time 5000 pumba-pinger-1"
```
