### ISSUE TITLE
Unable to run stressors with regex : flag provided but not defined: -cpu 1 --vm 1 --vm-bytes 500M --timeout 3m

### ISSUE THREAD

**Issue by uditgaurav** [alexei-led/pumba#174]
#### COMPONENT

- pumba stress

#### DETAILS:

- I was running pumba stress using the following spec:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pumba-stress
  labels:
    com.gaiaadm.pumba: "true"
spec:
  containers:
    # randomly pause containers in Pod named 'test-stress' every 3m for 1m
    - image: gaiaadm/pumba
      imagePullPolicy: IfNotPresent
      name: pumba-stress
      args:
        - --log-level
        - debug
        - stress
        - --duration
        - 1m
        - --stressors
        - --cpu 1 --vm 1 --vm-bytes 500M --timeout 3m    
        - re2:k8s_nginx_nginx-d69749d5c-htxsj

      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
      resources:
        requests:
          cpu: 10m
          memory: 5M
        limits:
          cpu: 100m
          memory: 20M
      volumeMounts:
        - name: dockersocket
          mountPath: /var/run/docker.sock
  volumes:
    - hostPath:
        path: /var/run/docker.sock
      name: dockersocket
```
**It is throwing error:**

_time="2020-09-09T13:27:17Z" level=fatal msg="flag provided but not defined: -cpu 1 --vm 1 --vm-bytes 500M --timeout 3m"_

It runs fine if we don't provide --stressors but --stressors along with regex give such an error. Can you please help me with what I'm missing.

**Note:**

- stressors with "--label" works fine but I need it in regex format "re2:k8s_nginx_nginx-d69749d5c-htxsj"
