### ISSUE TITLE
Deployment failed on Kubernetes 1.7

### ISSUE THREAD

**Issue by haithkris** [alexei-led/pumba#42]
When I try to deploy on Kubernetes, I got this kind of error: ` Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"pumba --interval 10s kill --signal SIGTERM containerName\\\\\\\": executable file not found in $PATH\\\"\\n\""}`  

Here's my deployment yaml file: 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pumba
spec:
  template:
    metadata:
      labels:
        app: pumba
      name: pumba
    spec:
      containers: 
      - image: gaiaadm/pumba
        imagePullPolicy: Always
        name: pumba
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
        command:
          - "pumba --interval 10s kill --signal SIGTERM containerName"
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
```
